### ISSUE TITLE
file [docker-compose.yml] not found

### ISSUE THREAD

**Issue by smaffiol** [EGA-archive/LocalEGA#123]
### Expected Behavior
trying to follow the documentation:
cd deploy
make -C bootstrap
make -j 4 images
make up

### Current Behavior
LocalEGA/deploy$ make up
file [docker-compose.yml] not found
make: *** [Makefile:11: up] Error 255

### Steps to Reproduce
cd deploy
make -C bootstrap
make -j 4 images
make up

### Context (Environment)
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

repo: origin	https://github.com/EGA-archive/LocalEGA.git

**Comment by silverdaz** [comment]
I think the bootstrap didn't work because LocalEGA doesn't use the file named `docker-compose.yml`. It instead uses 2 files named `lega.yml` and `pipeline.yml`, located in the `private` directory, created by the bootstrap, containing all the secrets. (Additionally, there is another docker-compose YAML file named `cega.yml` for the CentralEGA stub instances).

Can you check that you have the `.env` file in the `deploy` directory containing 
```
COMPOSE_PROJECT_NAME=lega
COMPOSE_FILE=private/lega.yml:private/cega.yml:private/pipeline.yml
COMPOSE_PATH_SEPARATOR=:

```

**Comment by silverdaz** [comment]
No answer from the original reporter, closing the issue
