### ISSUE TITLE
Add TLS termination

### ISSUE THREAD

**Issue by jbygdell** [EGA-archive/LocalEGA#37]
### Description

All communication between our services needs to be TLS terminated, including the cluster internal communication. As a result we can not rely on external PKI providers and thus must be able to supply a self signed CA root certificate unique for each deployment site.

### Proposed solution

Add options for each service to set a TLS certificate and corresponding CA root certificate.
These certificated should be mounted in at runtime.
### Definition of Done

All service communication is TLS terminated, including RabbitMQ and PostgreSQL

**Comment by silverdaz** [comment]
The database and message broker are already covered.
For the database, ssl is already enforced.
For the brokers, AMQP(s) is necessary to connect to the real CentralEGA broker, and for the local broker, it is supported but not turned on. This is fine for the local bootstrap (for testing and for travis), but necessary for the different deployments (ie this issue is not in the right repo).

The part related to the HTTP(s) exchanges with the keyserver is not covered already.
However, the keyserver will be deprecated in favor for secrets.
Therefore, I would not recommend to focus on this issue.

In shorter terms: Wait a bit and there will be no need to solve this issue.

**Comment by blankdots** [comment]
@jbygdell @silverdaz I suggest creating an issue for this on LocalEGA-mq, and if the keyserver is going to be deprecated in the future, it seems this issue could be placed in the backlog as `won't fix`, what say you ?

**Comment by blankdots** [comment]
tracked here: https://github.com/EGA-archive/LocalEGA-mq/issues/6
