### ISSUE TITLE
missing dependencies issue , cannot import name 'ed25519' , ImportError: No module named parse

### ISSUE THREAD

**Issue by wahbi** [EGA-archive/LocalEGA#78]
### Expected Behavior
make bootstrap ARGS='--pythonexec python3'

bootstrapping ...

### Current Behavior
ImportError: cannot import name 'ed25519'
Makefile:14: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 1

### Context (Environment)
trying to implement A LOCAL EGA using docker compose 
ubuntu 18.04 : python 3

**Comment by silverdaz** [comment]
I suspect this is related to the fact that Crypt4GH-related package were not installed.

LocalEGA does not use `ed25519`, it is instead defered to Crypt4GH.

The version of Crypt4GH, that LocalEGA currently uses, is outdated, and in the process of being upgraded. However, I'm surprised because this outdated version does not use Elliptic Curves, so I think you can dismiss the error entirely and wait for the upgrade.

**Comment by silverdaz** [comment]
There is now an upgrade, merged into master. Please use that one, and the issue should be gone.
