### ISSUE TITLE
ERROR: pgpy 0.5.2 has requirement cryptography>=2.6, but you'll have cryptography 2.3.1 which is incompatible.

### ISSUE THREAD

**Issue by wahbi** [EGA-archive/LocalEGA#79]
### Expected Behavior
this error came up and i tried to implement a localEGA with docker-compose , after running make -C images , everything went okay , except this error is worrying me ,
does this error has an effect on the mechanism of the system ?

**Comment by silverdaz** [comment]
The latest Crypt4GH encryption/decryption mechanism will not use `PGP`, so I'm not worried about this issue.

However, in order to help, the `pip install` command has probably tried to install the `cryptography` package and noticed that you already had it, although with an old version.

Try to remove it and re-install it. That should solve it.

**Comment by wahbi** [comment]
thank you .
